# Generated by Django 5.1.4 on 2025-01-02 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ambience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cuisine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(default="-1", max_length=22, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("account_since", models.DateField()),
                ("average_rating", models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="cuisine",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="alcohol",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "None"),
                    ("beer_wine", "Beer & Wine"),
                    ("full_bar", "Full Bar"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="attire",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="bike_parking",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="business_id",
            field=models.CharField(default="-1", max_length=22, unique=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="city",
            field=models.CharField(default="unkown", max_length=100),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="credit_cards_accepted",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="delivery",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="dogs_allowed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="friday_close",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="friday_open",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="good_for_groups",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="good_for_kids",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="happy_hour",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="is_open",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="monday_close",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="monday_open",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="outdoor_seating",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="parking",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="price_range",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="reservations",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="review_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="saturday_close",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="saturday_open",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="state",
            field=models.CharField(default="unkown", max_length=2),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="sunday_close",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="sunday_open",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="take_out",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="thursday_close",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="thursday_open",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="tuesday_close",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="tuesday_open",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="wednesday_close",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="wednesday_open",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="wheelchair_accessible",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="ambiences",
            field=models.ManyToManyField(
                blank=True, related_name="restaurants", to="app.ambience"
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="cuisines",
            field=models.ManyToManyField(
                blank=True, related_name="restaurants", to="app.cuisine"
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_id",
                    models.CharField(default="-1", max_length=22, unique=True),
                ),
                ("rating", models.FloatField()),
                ("date", models.DateField()),
                ("text", models.TextField()),
                (
                    "business_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="app.restaurant",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="app.user",
                    ),
                ),
            ],
        ),
    ]
