# Generated by Django 5.1.4 on 2025-01-05 20:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_restaurant_sustainable_alter_restaurant_alcohol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="attire",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="is_open",
        ),
    ]
